version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: aarush
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: crypto_sentiment
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
